# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" "i915"];
  boot.initrd.kernelModules = ["zfs"];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];
  boot.kernelParams = ["nohibernate" "pcie_aspm=off" "i915.enable_guc=2"];
  boot.zfs.package = pkgs.zfs_unstable;

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/11501f05-3030-40f8-88db-987999a6df84";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-3803de70-d8c4-424e-93ec-941c283a9df2".device = "/dev/disk/by-uuid/3803de70-d8c4-424e-93ec-941c283a9df2";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/1FDC-C194";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  fileSystems."/mnt/data" = {
    device = "datapool/encrypted/root";
    fsType = "zfs";
    options = ["default"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/2eb41016-c8b5-4de1-8d1c-0fbc3a59bd57";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  networking.interfaces.wlp0s20f0u5.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
